#!/usr/bin/env python3
"""
MESH-FLOW-RETOPOLOGY: Unified Scientific & Production Execution CLI
===================================================================
A unified command-line entry point to run:
1. End-to-End Retopology & OBJ Export (Demo Mode)
2. Comprehensive Multi-Archetype Benchmarking (Benchmark Mode)
3. GPU Flow Model Training Loop (Train Mode)
4. Blender 4.x / 5.x Add-on Health Check & Packaging (Blender Mode)
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path
from typing import Dict, Any, Tuple

import numpy as np

# Ensure runs/latest is in Python path for importing Phase 2 & 3 modules
WORKSPACE_ROOT = Path(__file__).resolve().parent
RUNS_LATEST = WORKSPACE_ROOT / "runs" / "latest"
if str(RUNS_LATEST) not in sys.path:
    sys.path.insert(0, str(RUNS_LATEST))

try:
    from dataset_pipeline import (
        AssetGeneratorSuite,
        StrainMechanicsExtractor,
        RigRetopoDataset,
    )
    from blender_retopo_addon import RetopoInferenceEngine
except ImportError as e:
    print(f"[ERROR] Failed to import core modules from runs/latest: {e}")
    sys.exit(1)


def export_obj_mesh(filepath: Path, verts: np.ndarray, quads: np.ndarray, comment: str = "") -> None:
    """Export vertices and quads to Wavefront OBJ format."""
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# Wavefront OBJ generated by MESH-FLOW-RETOPOLOGY\n")
        if comment:
            f.write(f"# {comment}\n")
        f.write(f"# Vertices: {len(verts)}, Quads: {len(quads)}\n\n")
        
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")
        
        for q in quads:
            # OBJ indices are 1-based
            f.write(f"f {q[0]+1} {q[1]+1} {q[2]+1} {q[3]+1}\n")


def run_demo(archetype: str, solver: str, steps: int, rings: int, segments: int, output_dir: Path) -> None:
    """Run single-archetype end-to-end retopology and export OBJ."""
    print("=" * 80)
    print(f"MESH-FLOW-RETOPOLOGY: DEMO EXECUTION ({archetype.upper()})")
    print(f"Solver: {solver} (Steps={steps}) | Resolution: Rings={rings}, Segments={segments}")
    print("=" * 80)
    
    # 1. Synthesize input high-resolution geometry & skeleton
    if archetype == "planar_hinge":
        data = AssetGeneratorSuite.generate_planar_hinge(num_high_points=2048)
    elif archetype == "articulated_limb":
        data = AssetGeneratorSuite.generate_articulated_limb(num_high_points=2048)
    elif archetype == "humanoid_smplx":
        data = AssetGeneratorSuite.generate_humanoid_archetype(num_high_points=2048)
    else:  # cylindrical_joint (default)
        data = AssetGeneratorSuite.generate_cylindrical_joint(num_high_points=2048)
        
    high_pts = data["high_points"]
    high_nrms = data["high_normals"]
    joints = data["joint_positions"]
    
    print(f"  [1] High-poly Surface:   {high_pts.shape[0]} sampled points + unit normals")
    print(f"  [2] Kinematic Skeleton:  {joints.shape[0]} articulation joints")
    
    # 2. Run Parallel ODE Flow Retopology Solver
    t0 = time.perf_counter()
    verts, quads, weights = RetopoInferenceEngine.generate_quad_topology(
        target_pts=high_pts,
        joint_positions=joints,
        num_rings=rings,
        radial_seg=segments,
        solver_type=solver,
        ode_steps=steps,
        lambda_strain=0.25,
    )
    solve_ms = (time.perf_counter() - t0) * 1000.0
    
    # 3. Evaluate Topology Quality Metrics
    metrics = RetopoInferenceEngine.evaluate_topology_metrics(verts, quads)
    
    # 4. Export OBJ files
    out_quad_obj = output_dir / f"{archetype}_flow_retopo.obj"
    export_obj_mesh(
        out_quad_obj,
        verts,
        quads,
        comment=f"Archetype: {archetype}, Q%={metrics['quad_ratio']:.1f}%, V4%={metrics['valence_4_pct']:.1f}%"
    )
    
    print(f"\n[RESULTS & VERIFICATION]")
    print(f"  • Generated Vertices:    {metrics['vertex_count']}")
    print(f"  • Generated Quad Faces:  {metrics['face_count']}")
    print(f"  • Quad Ratio (Q%):       {metrics['quad_ratio']:.2f}%  (Target: >= 98.0%)")
    print(f"  • Valence-4 Ratio (V4%): {metrics['valence_4_pct']:.2f}%  (Target: >= 90.0%)")
    print(f"  • Solve Latency:         {solve_ms:.2f} ms")
    print(f"  • Exported Mesh OBJ:     {out_quad_obj.resolve()}")
    print("=" * 80)


def run_benchmarks() -> None:
    """Run comparative multi-archetype evaluation and print summary."""
    print("=" * 90)
    print("MESH-FLOW-RETOPOLOGY: MULTI-ARCHETYPE BENCHMARK EVALUATION")
    print("=" * 90)
    
    archetypes = [
        ("planar_hinge", "Planar Hinge (1-DOF)"),
        ("cylindrical_joint", "Cylindrical Joint (Elbow/Knee)"),
        ("articulated_limb", "Articulated Limb (Arm/Forearm/Hand)"),
        ("humanoid_smplx", "Humanoid SMPL-X (17 Joints)"),
    ]
    
    results = []
    
    for key, name in archetypes:
        t0 = time.perf_counter()
        if key == "planar_hinge":
            data = AssetGeneratorSuite.generate_planar_hinge(num_high_points=2048)
            rings, segs = 15, 15
        elif key == "articulated_limb":
            data = AssetGeneratorSuite.generate_articulated_limb(num_high_points=2048)
            rings, segs = 24, 16
        elif key == "humanoid_smplx":
            data = AssetGeneratorSuite.generate_humanoid_archetype(num_high_points=2048)
            rings, segs = 16, 12
        else:
            data = AssetGeneratorSuite.generate_cylindrical_joint(num_high_points=2048)
            rings, segs = 20, 16
            
        high_pts = data["high_points"]
        joints = data["joint_positions"]
        
        verts, quads, weights = RetopoInferenceEngine.generate_quad_topology(
            target_pts=high_pts,
            joint_positions=joints,
            num_rings=rings,
            radial_seg=segs,
            solver_type="Midpoint",
            ode_steps=10,
            lambda_strain=0.25,
        )
        dt_ms = (time.perf_counter() - t0) * 1000.0
        m = RetopoInferenceEngine.evaluate_topology_metrics(verts, quads)
        
        results.append({
            "name": name,
            "verts": m["vertex_count"],
            "quads": m["face_count"],
            "q_pct": m["quad_ratio"],
            "v4_pct": m["valence_4_pct"],
            "latency": dt_ms,
        })
        
    print(f"\n{'Archetype Benchmark':<35} | {'Verts':<6} | {'Quads':<6} | {'Q %':<8} | {'V4 %':<8} | {'Latency':<10}")
    print("-" * 90)
    for r in results:
        print(f"{r['name']:<35} | {r['verts']:<6} | {r['quads']:<6} | {r['q_pct']:<8.1f} | {r['v4_pct']:<8.1f} | {r['latency']:<7.2f} ms")
    print("=" * 90)
    print("These rows are the analytic cylinder lattice. Quad ratio is 100% by construction.")
    print("This command does not load FlowRetopoDiT and does not decide a research gate.")


def main() -> None:
    parser = argparse.ArgumentParser(description="MESH-FLOW-RETOPOLOGY Unified Runner")
    parser.add_argument("--mode", choices=["demo", "benchmark", "train"], default="demo", help="Execution mode")
    parser.add_argument("--archetype", choices=["planar_hinge", "cylindrical_joint", "articulated_limb", "humanoid_smplx"], default="cylindrical_joint", help="Archetype for demo")
    parser.add_argument("--solver", choices=["Euler", "Midpoint", "Heun"], default="Midpoint", help="ODE numerical integrator")
    parser.add_argument("--steps", type=int, default=10, help="ODE integration step count")
    parser.add_argument("--rings", type=int, default=20, help="Concentric ring loop count")
    parser.add_argument("--segments", type=int, default=16, help="Radial quad segment count")
    parser.add_argument("--outdir", type=str, default="output", help="Directory to save generated OBJ files")
    parser.add_argument("--train-steps", type=int, default=100, help="Training steps (for train mode)")
    args = parser.parse_args()

    out_path = Path(args.outdir)

    if args.mode == "demo":
        run_demo(
            archetype=args.archetype,
            solver=args.solver,
            steps=args.steps,
            rings=args.rings,
            segments=args.segments,
            output_dir=out_path,
        )
    elif args.mode == "benchmark":
        run_benchmarks()
    elif args.mode == "train":
        try:
            from train_flow_retopo import run_training_experiment
            run_training_experiment(total_steps=args.train_steps)
        except Exception as e:
            print(f"[ERROR] Training execution failed: {e}")
            sys.exit(1)


if __name__ == "__main__":
    main()
